name: Unzip

on:
  push:
    paths:
      - "*.zip"

jobs:
  unzip:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Repository auschecken
        uses: actions/checkout@v4

      - name: ZIP entpacken
        run: |
          unzip -o *.zip -d extracted
          rm *.zip

      - name: Änderungen speichern
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Unzip uploaded files" || exit 0
          git push